language: python
env:
  matrix:
  - TOXENV=py27-django18
  - TOXENV=py27-django19
  - TOXENV=py27-django110
  - TOXENV=py34-django18
  - TOXENV=py34-django19
  - TOXENV=py34-django110
  - TOXENV=py35-django18
  - TOXENV=py35-django19
  - TOXENV=py35-django110
  - TOXENV=flake8
  - TOXENV=readme
install:
- make develop
script:
- make test
